#baseURL = "https://jumarque.42.fr/static"
title = "42 fitness"
theme = "hugo-coder"
paginate = 8
canonifyURLs = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

[params]
  author = "JJ Marquez"
  description = "Student @42Malaga && fitness addict"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/ElWare"